name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, portfolio-cloudserver]

    steps:
      - name: Deploy
        run: |
          cd /opt/docker-sites/portfolio
          git pull origin main

          docker compose build app
          docker compose up -d

          docker exec portfolio_app bash -lc "cd /var/www && composer install --no-dev --optimize-autoloader"
          docker exec portfolio_app bash -lc "cd /var/www && php artisan optimize:clear"

          npm install
          npm run build